export const AVAILABLE_AVATARS = [
  { id: 'avatar1', emoji: '🦊', name: 'Fox', color: '#FF6B35' },
  { id: 'avatar2', emoji: '🐼', name: 'Panda', color: '#4ECDC4' },
  { id: 'avatar3', emoji: '🦁', name: 'Lion', color: '#FFD93D' },
  { id: 'avatar4', emoji: '🐯', name: 'Tiger', color: '#FF8C42' },
  { id: 'avatar5', emoji: '🐨', name: 'Koala', color: '#95B8D1' },
  { id: 'avatar6', emoji: '🐸', name: 'Frog', color: '#90EE90' },
  { id: 'avatar7', emoji: '🦄', name: 'Unicorn', color: '#E0BBE4' },
  { id: 'avatar8', emoji: '🐵', name: 'Monkey', color: '#D4A373' },
  { id: 'avatar9', emoji: '🦉', name: 'Owl', color: '#8B7355' },
  { id: 'avatar10', emoji: '🐙', name: 'Octopus', color: '#D946EF' },
  { id: 'avatar11', emoji: '🦋', name: 'Butterfly', color: '#FF69B4' },
  { id: 'avatar12', emoji: '🐝', name: 'Bee', color: '#FFD700' },
  { id: 'avatar13', emoji: '🦕', name: 'Dinosaur', color: '#77DD77' },
  { id: 'avatar14', emoji: '🐬', name: 'Dolphin', color: '#4169E1' },
  { id: 'avatar15', emoji: '🦭', name: 'Seal', color: '#778899' },
  { id: 'avatar16', emoji: '🐧', name: 'Penguin', color: '#000000' },
  { id: 'avatar17', emoji: '🦚', name: 'Peacock', color: '#0080FF' },
  { id: 'avatar18', emoji: '🦜', name: 'Parrot', color: '#32CD32' },
  { id: 'avatar19', emoji: '🦩', name: 'Flamingo', color: '#FF69B4' },
  { id: 'avatar20', emoji: '🐢', name: 'Turtle', color: '#2E8B57' },
  { id: 'avatar21', emoji: '🦎', name: 'Lizard', color: '#6B8E23' },
  { id: 'avatar22', emoji: '🐍', name: 'Snake', color: '#556B2F' },
  { id: 'avatar23', emoji: '🦓', name: 'Zebra', color: '#000000' },
  { id: 'avatar24', emoji: '🦒', name: 'Giraffe', color: '#FFB347' },
  { id: 'avatar25', emoji: '🦘', name: 'Kangaroo', color: '#CD853F' },
  { id: 'avatar26', emoji: '🦫', name: 'Beaver', color: '#8B4513' },
  { id: 'avatar27', emoji: '🦦', name: 'Otter', color: '#A0522D' },
  { id: 'avatar28', emoji: '🦥', name: 'Sloth', color: '#BC8F8F' },
  { id: 'avatar29', emoji: '🦇', name: 'Bat', color: '#4B0082' },
  { id: 'avatar30', emoji: '🐺', name: 'Wolf', color: '#808080' },
  { id: 'avatar31', emoji: '🦊', name: 'Red Fox', color: '#FF4500' },
  { id: 'avatar32', emoji: '🦝', name: 'Raccoon', color: '#696969' },
  { id: 'avatar33', emoji: '🐻', name: 'Bear', color: '#8B4513' },
  { id: 'avatar34', emoji: '🐻‍❄️', name: 'Polar Bear', color: '#F0FFFF' },
  { id: 'avatar35', emoji: '🦌', name: 'Deer', color: '#DEB887' },
  { id: 'avatar36', emoji: '🐰', name: 'Rabbit', color: '#FFB6C1' },
  { id: 'avatar37', emoji: '🦔', name: 'Hedgehog', color: '#8B7355' },
  { id: 'avatar38', emoji: '🐿️', name: 'Squirrel', color: '#D2691E' },
  { id: 'avatar39', emoji: '🦎', name: 'Gecko', color: '#00CED1' },
  { id: 'avatar40', emoji: '🐉', name: 'Dragon', color: '#FF0000' },
];

export const getAvatarById = (id) => {
  return AVAILABLE_AVATARS.find((avatar) => avatar.id === id) || AVAILABLE_AVATARS[0];
};
